

<form action="<?= BASE_URL ?>agregar-gestion" method="POST" class="filter-form">
    <h2 class="filter-header">Formulario para Agregar una nueva gestión</h2>

    <div class="filter-grid">
        <div class="filter-group">
            <label for="fecha">Fecha:</label>
            <input type="date" id="fecha" name="fecha">
        </div>

        <div class="filter-group">
            <label for="id_cuenta">Cuenta:</label>
            <select id="id_cuenta" name="id_cuenta" required>
                <option value="" disabled selected>Seleccione una cuenta</option>
                <?php foreach ($cuentas as $cuenta): ?>
                    <option value="<?= $cuenta->id?>"><?= $cuenta->cuenta ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="filter-group">
            <label for="descripcion">Descripción:</label>
            <input type="text" id="descripcion" name="descripcion" required>
        </div>

        <div class="filter-group">
            <label for="ingreso_efectivo">Ingreso Efectivo:</label>
            <input type="number" id="ingreso_efectivo" name="ingreso_efectivo" step="0.01" min="0">
        </div>

        <div class="filter-group">
            <label for="egreso_efectivo">Egreso Efectivo:</label>
            <input type="number" id="egreso_efectivo" name="egreso_efectivo" step="0.01" min="0">
        </div>

        <div class="filter-group">
            <label for="ingreso_banco">Ingreso Banco:</label>
            <input type="number" id="ingreso_banco" name="ingreso_banco" step="0.01" min="0">
        </div>

        <div class="filter-group">
            <label for="egreso_banco">Egreso Banco:</label>
            <input type="number" id="egreso_banco" name="egreso_banco" step="0.01" min="0">
        </div>

        <div class="filter-group">
            <label for="ingreso_usd">Ingreso USD:</label>
            <input type="number" id="ingreso_usd" name="ingreso_usd" step="0.01" min="0">
        </div>

        <div class="filter-group">
            <label for="egreso_usd">Egreso USD:</label>
            <input type="number" id="egreso_usd" name="egreso_usd" step="0.01" min="0">
        </div>
        
    <div class="filter-actions">
        <button type="submit" class="btn-guardar">Guardar</button>
        <a href="<?= BASE_URL ?>tabla-gestion" class="btn-cancelar">Cancelar</a>
    </div>
    </div>
</form>
