<main>
    <h1>Bienvenido a la Gestión de Juliettt</h1>
    <p>Utilice el menú para navegar por las diferentes secciones.</p>

    <div class="home-grid">
        
      <section onclick="location.href='<?= BASE_URL ?>tabla-gestion'">

            <div class="card">
                <h2>Tabla de gastos</h2>
            </div>
        </section>
        <section onclick="location.href='<?= BASE_URL ?>tabla-cotizaciones'">
            <div class="card">
                <h2>Tabla de Usd</h2>
            </div>
        </section>
    </div>
</main>


